version: '3.3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
  cop:
    image: tokend/traefik-cop:1.0.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
    - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8000:80"
  core:
    image: tokend/core:3.7.0
    depends_on:
      - traefik
    restart: unless-stopped
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=core
      - POSTGRES_DB=core
      - PGDATA=/data/pgdata
      - ENSUREDB=1
      - CONFIG=/core-config.ini
    volumes:
      - ./configs/core.ini:/core-config.ini
      - core-data:/data
    labels:
      - "autoheal=true"
  horizon:
    image: tokend/horizon:3.10.0
    depends_on:
      - core
    restart: unless-stopped
    environment:
      - POSTGRES_USER=horizon
      - POSTGRES_PASSWORD=horizon
      - POSTGRES_DB=horizon
      - PGDATA=/data/pgdata
    volumes:
      - ./configs/horizon.yaml:/config.yaml
      - horizon-data:/data
    ports: 
      - 8028:80

  password-api:
    image: ghcr.io/lisabestteam/password-svc:9e4b13b468de8bbf9c098013a934a639365474bb
    restart: unless-stopped
    depends_on:
      - horizon
      - password_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/password.yaml:/config.yaml
    entrypoint: sh -c "password run service server"
    ports:
      - 8012:80
    
  password-ingest:
    image: ghcr.io/lisabestteam/password-svc:9e4b13b468de8bbf9c098013a934a639365474bb
    restart: unless-stopped
    depends_on:
      - horizon
      - password_db
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/password.yaml:/config.yaml
    entrypoint: sh -c "password migrate up && password run service ingest"
    

  password_db:
    image: tokend/postgres-ubuntu:9.6
    restart: unless-stopped
    environment:
      - POSTGRES_USER=password
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=password
      - PGDATA=/pgdata
    volumes:
      - password-data:/pgdata
    

volumes:
  core-data:
  horizon-data:
  password-data: