db:
  url: postgres://password:password@password_db/password?sslmode=disable

log:
  disable_sentry: true
  level: info


horizon:
  endpoint: http://horizon

listener:
  addr: :80

cop:
  disabled: false
  endpoint: http://cop
  upstream: http://password-api
  service_name: "password-api"
  service_prefix: "/integrations/password"
  service_port: "80"
